name: flutter_subscreen_plugin
description: 支持双屏安卓设备，主副屏均使用 flutter 进行开发，提供双屏通信能力
version: 1.3.2+2
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/flutter_subscreen_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rex.flutter_subscreen_plugin
        pluginClass: FlutterSubscreenPlugin
